{
  "formatVersion": "1.1",
  "component": {
    "url": "../../awesome-navigation/1.0.1/awesome-navigation-1.0.1.module",
    "group": "awesome.navigation",
    "module": "awesome-navigation",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "awesome-navigation-android-1.0.1.aar",
          "size": 86486,
          "sha512": "66ee0c5d106ed6a977f122b1d1fdfde4fcde542d911d839f66b88e03b0296e1144c4c326bd648060f4739d643a6e0cf0cf3f2a137a1221096d74f80435ac6735",
          "sha256": "2e7e267dacb12e965ac65bf0f5b368944c3fcd748e64820d4e6aa61a0bc06b0f",
          "sha1": "354916eb8ba1b96b16c889332dd09805f20031c3",
          "md5": "f295e333ff7d5551dec9e139e691811c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared.aar",
          "url": "awesome-navigation-android-1.0.1.aar",
          "size": 86486,
          "sha512": "66ee0c5d106ed6a977f122b1d1fdfde4fcde542d911d839f66b88e03b0296e1144c4c326bd648060f4739d643a6e0cf0cf3f2a137a1221096d74f80435ac6735",
          "sha256": "2e7e267dacb12e965ac65bf0f5b368944c3fcd748e64820d4e6aa61a0bc06b0f",
          "sha1": "354916eb8ba1b96b16c889332dd09805f20031c3",
          "md5": "f295e333ff7d5551dec9e139e691811c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      }
    }
  ]
}
