{
  "formatVersion": "1.1",
  "component": {
    "url": "../../awesome-navigation/1.0.1/awesome-navigation-1.0.1.module",
    "group": "awesome.navigation",
    "module": "awesome-navigation",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iosSimulatorArm64Main.klib",
          "url": "shared-iossimulatorarm64-1.0.1.klib",
          "size": 84479,
          "sha512": "e36bbd49bc104c2315eed90a20bb8334559f52bf2267f1dd27b8d6fa153bbebd9f2fec00dacb6feaf112d00e32c064d1ae81ef6e8e090bd6eb78323b8d1b9b76",
          "sha256": "981ab090172652affc2488f57cefa8dfa4880283b0dfa73d87da4e76d4b91b4f",
          "sha1": "6377e717f02e13dd24133d2fbd6f68e79af68a65",
          "md5": "555fe034041c9dd71ac2f313c7a7870c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-backhandler",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-iossimulatorarm64-metadata.jar",
          "url": "shared-iossimulatorarm64-1.0.1-metadata.jar",
          "size": 2434,
          "sha512": "47effc569a5dddf3b9e81d0a62d5892b25e32415de8113525f7518377d1a3565a8f8c1c348a196342459d18941d3fd80383ccc4bbe18e96c54e7bca4d30f8300",
          "sha256": "62f09984863bb519ef78c26153f0b0a5aea3a07a082384958051610ab0ac9ea1",
          "sha1": "1c4e747af279489260e5de0fa569926378bff4d9",
          "md5": "dd2c17390831d807b3dd6cda0ceb4a2c"
        }
      ]
    }
  ]
}
