{
  "formatVersion": "1.1",
  "component": {
    "group": "awesome.navigation",
    "module": "navigation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-1.0.0.aar",
          "url": "navigation-1.0.0.aar",
          "size": 73371,
          "sha512": "8a6509d334908b6547a10a67e30ac62bc452fd2c3db79f1ffd4781e534a08095a6961c69e2abca10d9e22e0b6c82c7a7e09766b57f15513742fb70ccc3f6c379",
          "sha256": "b00c8eb9612601a72dec80b4a8cfbb6536db43b39d15ce43029675caeb100176",
          "sha1": "84e9be581ac0f41745c0c3460a5993e30961ae9a",
          "md5": "117d0206b2e9bdac6f065447dd3b47d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.02.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-1.0.0.aar",
          "url": "navigation-1.0.0.aar",
          "size": 73371,
          "sha512": "8a6509d334908b6547a10a67e30ac62bc452fd2c3db79f1ffd4781e534a08095a6961c69e2abca10d9e22e0b6c82c7a7e09766b57f15513742fb70ccc3f6c379",
          "sha256": "b00c8eb9612601a72dec80b4a8cfbb6536db43b39d15ce43029675caeb100176",
          "sha1": "84e9be581ac0f41745c0c3460a5993e30961ae9a",
          "md5": "117d0206b2e9bdac6f065447dd3b47d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-1.0.0-javadoc.jar",
          "url": "navigation-1.0.0-javadoc.jar",
          "size": 330772,
          "sha512": "bcad372562f67672836fa5a5e997b6320f0b266f87463c3f328b0f00e3138900382bb7c1e0867458288973c0210186ecdf58c78606d8b5b62801aa02c21d96f8",
          "sha256": "ec30432b3dde9cd26ce71c0353a8c29ac3cf6060dac8e026db60ae276e608f20",
          "sha1": "ba7ec9bc55e08ac5ea444c059e0886e9e72f81a1",
          "md5": "ef843bb4b7eaf01e5b24e43bc9d967f7"
        }
      ]
    }
  ]
}
